Indentation adjustment

diff --git a/bin/buildarmimg b/bin/buildarmimg
--- a/bin/buildarmimg
+++ b/bin/buildarmimg
@@ -25,63 +25,63 @@ check_running
 opt=":e:d:v:i:b:nfxhk:mos:p:cz:"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     c)
-      COLORS='true'
-      ;;
+        COLORS='true'
+        ;;
     e)
-      EDITION="${OPTARG}"
-      ;;
+        EDITION="${OPTARG}"
+        ;;
     d)
-      DEVICE="${OPTARG}"
-      ;;
+        DEVICE="${OPTARG}"
+        ;;
     v)
-      VERSION="${OPTARG}"
-      ;;
+        VERSION="${OPTARG}"
+        ;;
     n)
-      KEEPROOTFS='false'
-      ;;
+        KEEPROOTFS='false'
+        ;;
     x)
-      EXTRACTED='true'
-      ;;
+        EXTRACTED='true'
+        ;;
     i)
-      ADD_PACKAGES="${OPTARG}"
-      check_local_pkgs
-      ;;
+        ADD_PACKAGES="${OPTARG}"
+        check_local_pkgs
+        ;;
     b)
-      BRANCH="${OPTARG}"
-      ;;
+        BRANCH="${OPTARG}"
+        ;;
     f)
-      FACTORY='true'
-      ;;
+        FACTORY='true'
+        ;;
     m)
-      BMAP='true'
-     ;;
+        BMAP='true'
+        ;;
     k)
-      CUSTOM_REPO="${OPTARG}"
-     ;;
+        CUSTOM_REPO="${OPTARG}"
+        ;;
     s)
-      HOSTNAME="${OPTARG}"
-     ;;
+        HOSTNAME="${OPTARG}"
+        ;;
     p)
-      FILESYSTEM="${OPTARG}"
-      ;;
+        FILESYSTEM="${OPTARG}"
+        ;;
     z)
-      COMPRESSION="${OPTARG}"
-      ;;
+        COMPRESSION="${OPTARG}"
+        ;;
     \?)
-      echo "Option -${OPTARG} is not valid, aborting"
-      exit 1
-      ;;
-    h|?)
-      usage_build_img
-      exit 1
-      ;;
+        echo "Option -${OPTARG} is not valid, aborting"
+        exit 1
+        ;;
+    h | ?)
+        usage_build_img
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 [[ "$COLORS" = "true" ]] && enable_colors
@@ -107,20 +107,20 @@ timer_start=$(get_timer)
 PKG_DEVICE=$(grep "^[^#;]" $PROFILES/biglinux-arm-profiles/devices/$DEVICE | awk '{print $1}')
 PKG_SHARED=$(grep "^[^#;]" $PROFILES/biglinux-arm-profiles/editions/shared | sed -e 's/>'${DEVICE//pro/}' //' -e '/^>/d' -e 's/#.*//')
 PKG_EDITION=$(grep "^[^#;]" $PROFILES/biglinux-arm-profiles/editions/$EDITION | sed -e 's/>'${DEVICE//pro/}' //' -e '/^>/d' -e 's/#.*//')
-cat $PROFILES/biglinux-arm-profiles/services/$EDITION \
-    | sed -e '/^#/d' -e 's/>'${DEVICE//pro/}' //' -e '/^>/d' -e 's/#.*//' \
-    > $SERVICES_LIST
+cat $PROFILES/biglinux-arm-profiles/services/$EDITION |
+    sed -e '/^#/d' -e 's/>'${DEVICE//pro/}' //' -e '/^>/d' -e 's/#.*//' \
+        >$SERVICES_LIST
 
 # Create the rootfs used for the image
 create_rootfs_img 2>&1 | tee --append "$LOGFILE"
 
 case "$DEVICE" in
-    halium-9)
-        create_img_halium 2>&1 | tee --append "$LOGFILE"
-        ;;
-    *)
-        create_img 2>&1 | tee --append "$LOGFILE"
-        ;;
+halium-9)
+    create_img_halium 2>&1 | tee --append "$LOGFILE"
+    ;;
+*)
+    create_img 2>&1 | tee --append "$LOGFILE"
+    ;;
 esac
 
 if [ $BMAP = true ]; then
diff --git a/bin/buildarmpkg b/bin/buildarmpkg
--- a/bin/buildarmpkg
+++ b/bin/buildarmpkg
@@ -22,50 +22,50 @@ check_running
 opt=":p:a:i:r:nb:kh"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     p)
-      PACKAGE="${OPTARG%/}"
-      ;;
+        PACKAGE="${OPTARG%/}"
+        ;;
     a)
-      ARCH="${OPTARG}"
-      ;;
+        ARCH="${OPTARG}"
+        ;;
     k)
-      BUILDCLEAN=false
-      ;;
+        BUILDCLEAN=false
+        ;;
     b)
-      BRANCH="${OPTARG}"
-      ;;
+        BRANCH="${OPTARG}"
+        ;;
     i)
-      ADD_PACKAGES="${OPTARG}"
-      check_local_pkgs
-      ;;
+        ADD_PACKAGES="${OPTARG}"
+        check_local_pkgs
+        ;;
     n)
-      INSTALL_NEW=true
-      ;;
+        INSTALL_NEW=true
+        ;;
     r)
-      CUSTOM_REPO="${OPTARG}"
-     ;;
+        CUSTOM_REPO="${OPTARG}"
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}"
-      exit 1
-      ;;
-    h|?)
-      usage_build_pkg
-      exit 1
-      ;;
+        echo "Invalid option: -${OPTARG}"
+        exit 1
+        ;;
+    h | ?)
+        usage_build_pkg
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 enable_colors
 
 # Both package and architecture are needed
 if [ "x" == "x$PACKAGE" ]; then
-  echo "Option -p must be specified, aborting"
-  exit
+    echo "Option -p must be specified, aborting"
+    exit
 fi
 
 # Build the 'any' packages on aarch64
@@ -78,7 +78,7 @@ check_branch
 
 # Start the timer
 timer_start=$(get_timer)
-   
+
 if [[ "$BUILDCLEAN" = "false" && ! -d $CHROOTDIR ]]; then
     msg "Rootfs not found, aborting; omit the -k option to generate a rootfs"
     exit 1
diff --git a/bin/builddockerimg b/bin/builddockerimg
--- a/bin/builddockerimg
+++ b/bin/builddockerimg
@@ -15,7 +15,7 @@ check_root
 # check if script is already running
 check_running
 
-create_rootfs () {
+create_rootfs() {
     # Remove old rootfs if it exists
     if [ -d $BUILDDIR/$ARCH ]; then
         echo "Removing old rootfs..."
@@ -30,27 +30,27 @@ create_rootfs () {
 
     # Enable cross-architecture chrooting
     cp -a /usr/bin/qemu-aarch64-static $BUILDDIR/$ARCH/usr/bin
-    
+
     # Fix SSL in the rootfs
     rm -f $BUILDDIR/$ARCH/etc/ssl/certs/ca-certificates.crt
     rm -f $BUILDDIR/$ARCH/etc/ca-certificates/extracted/tls-ca-bundle.pem
     cp -a /etc/ssl/certs/ca-certificates.crt $BUILDDIR/$ARCH/etc/ssl/certs
     cp -a /etc/ca-certificates/extracted/tls-ca-bundle.pem $BUILDDIR/$ARCH/etc/ca-certificates/extracted
-    
+
     info "Setting up keyrings..."
-    $NSPAWN $BUILDDIR/$ARCH pacman-key --init > /dev/null 2>&1
-    $NSPAWN $BUILDDIR/$ARCH pacman-key --populate archlinuxarm manjaro manjaro-arm > /dev/null 2>&1
-    $NSPAWN $BUILDDIR/$ARCH pacman-mirrors -f5 > /dev/null 2>&1
+    $NSPAWN $BUILDDIR/$ARCH pacman-key --init >/dev/null 2>&1
+    $NSPAWN $BUILDDIR/$ARCH pacman-key --populate archlinuxarm manjaro manjaro-arm >/dev/null 2>&1
+    $NSPAWN $BUILDDIR/$ARCH pacman-mirrors -f5 >/dev/null 2>&1
 }
 
-compress_docker () {
+compress_docker() {
     msg "Making Docker image..."
 
     # Make sure that Docker service is running
     systemctl start docker
 
     # Create the Docker image itself
-    tar --numeric-owner --xattrs --acls -C $BUILDDIR/$ARCH -c . | docker import - $DOCKER_IMAGE_NAME > /dev/null 2>&1
+    tar --numeric-owner --xattrs --acls -C $BUILDDIR/$ARCH -c . | docker import - $DOCKER_IMAGE_NAME >/dev/null 2>&1
     docker image tag $DOCKER_IMAGE_NAME:latest manjaroarm/$DOCKER_IMAGE_NAME:latest
 
     # Upload the Docker image to DockerHub and remove it locally
@@ -63,23 +63,23 @@ compress_docker () {
 opt=":a:h"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     a)
-      ARCH="${OPTARG}"
-      ;;
+        ARCH="${OPTARG}"
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}"
-      exit 1
-      ;;
-    h|?)
-      echo "-h <help>       This help"
-      exit 1
-      ;;
+        echo "Invalid option: -${OPTARG}"
+        exit 1
+        ;;
+    h | ?)
+        echo "-h <help>       This help"
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 # Log file
diff --git a/bin/buildemmcinstaller b/bin/buildemmcinstaller
--- a/bin/buildemmcinstaller
+++ b/bin/buildemmcinstaller
@@ -22,50 +22,50 @@ check_running
 opt=":e:d:v:i:f:nxh"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     e)
-      EDITION="${OPTARG}"
-      ;;
+        EDITION="${OPTARG}"
+        ;;
     d)
-      DEVICE="${OPTARG}"
-      ;;
+        DEVICE="${OPTARG}"
+        ;;
     v)
-      VERSION="${OPTARG}"
-      ;;
+        VERSION="${OPTARG}"
+        ;;
     n)
-      KEEPROOTFS=false
-      ;;
+        KEEPROOTFS=false
+        ;;
     x)
-      EXTRACTED=true
-      ;;
+        EXTRACTED=true
+        ;;
     i)
-      ADD_PACKAGES="${OPTARG}"
-      check_local_pkgs
-      ;;
+        ADD_PACKAGES="${OPTARG}"
+        check_local_pkgs
+        ;;
     f)
-      FLASHVERSION="${OPTARG}"
-      ;;
+        FLASHVERSION="${OPTARG}"
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}"
-      exit 1
-      ;;
-    h|?)
-      echo "Only works with existing images on OSDN.net"
-      usage_build_emmcflasher
-      exit 1
-      ;;
+        echo "Invalid option: -${OPTARG}"
+        exit 1
+        ;;
+    h | ?)
+        echo "Only works with existing images on OSDN.net"
+        usage_build_emmcflasher
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 enable_colors
 
 if [ "x" == "x$VERSION" ]; then
-  echo "-v [option] is required"
-  exit
+    echo "-v [option] is required"
+    exit
 fi
 
 IMGNAME="BigLinux-ARM-$EDITION-$DEVICE-$VERSION-emmc-installer-$FLASHVERSION"
@@ -82,7 +82,7 @@ timer_start=$(get_timer)
 PKG_DEVICE=$(grep "^[^#;]" $PROFILES/biglinux-arm-profiles/devices/$DEVICE | awk '{print $1}')
 PKG_EDITION=$(grep "^[^#;]" $PROFILES/biglinux-arm-profiles/editions/minimal | awk '{print $1}')
 SRV_EDITION=$(grep "^[^#;]" $PROFILES/biglinux-arm-profiles/services/minimal | awk '{print $1}')
-cat $PROFILES/biglinux-arm-profiles/services/minimal | sed -e '/^#/d' > $SERVICES_LIST
+cat $PROFILES/biglinux-arm-profiles/services/minimal | sed -e '/^#/d' >$SERVICES_LIST
 
 # Create the rootfs used for the image
 create_emmc_install
diff --git a/bin/buildrootfs b/bin/buildrootfs
--- a/bin/buildrootfs
+++ b/bin/buildrootfs
@@ -5,7 +5,7 @@ LIBDIR=/usr/share/biglinux-arm-tools/lib
 ARCH="aarch64"
 
 # Import the library
-source $LIBDIR/functions.sh 
+source $LIBDIR/functions.sh
 enable_colors
 
 # Check for root
@@ -14,7 +14,7 @@ check_root
 # Check is the script already running
 check_running
 
-create_rootfs () {
+create_rootfs() {
     # Remove old rootfs if it exists
     if [ -d $BUILDDIR/$ARCH ]; then
         echo "Removing old rootfs..."
@@ -25,34 +25,34 @@ create_rootfs () {
     msg "Creating rootfs..."
     mkdir -p $BUILDDIR/$ARCH/etc
     $CHROOTDIR pacman-key --init
-    $LIBDIR/pacstrap -G -M -C $LIBDIR/pacman.conf.$ARCH $BUILDDIR/$ARCH pacman biglinux-arm-keyring 
+    $LIBDIR/pacstrap -G -M -C $LIBDIR/pacman.conf.$ARCH $BUILDDIR/$ARCH pacman biglinux-arm-keyring
 
     # Enable cross-architecture chrooting
     cp -a /usr/bin/qemu-aarch64-static $BUILDDIR/$ARCH/usr/bin
-    
+
     # Fix SSL in the rootfs
     $NSPAWN $BUILDDIR/$ARCH update-ca-trust
-    
+
     rm -f $BUILDDIR/$ARCH/var/cache/pacman/pkg/*
-    $NSPAWN $BUILDDIR/$ARCH pacman-mirrors -f5 > /dev/null 2>&1
+    $NSPAWN $BUILDDIR/$ARCH pacman-mirrors -f5 >/dev/null 2>&1
 }
 
-biglinux_rootfs () {
-  msg "BigLinux Changes..."
+biglinux_rootfs() {
+    msg "BigLinux Changes..."
 
-  # BigLinux Information
-  sed -i 's|^Manjaro Linux|BigLinux, based in Manjaro Linux|g' $BUILDDIR/$ARCH/etc/issue
-  sed -i 's|^ *\bNAME\b *=.*|NAME="BigLinux based in Manjaro Linux"|;s|^ *\ID\b *=.*|ID="biglinux-arm"|;s|^ *\ID_LIKE\b *=.*|ID_LIKE="biglinux arch"|;s|^ *\bPRETTY_NAME\b *=.*|PRETTY_NAME="BigLinux based in Manjaro Linux"|;s|^ *\ANSI_COLOR\b *=.*|ANSI_COLOR="32;1;24;144;200"|;s|^ *\bHOME_URL\b *=.*|HOME_URL="https://www.biglinux.com.br"|;s|^ *\bSUPPORT_URL\b *=.*|SUPPORT_URL="https://forum.biglinux.com.br"|;s|^ *\LOGO\b *=.*|LOGO="biglinux-blue"|' $BUILDDIR/$ARCH/usr/lib/os-release
-  sed -i 's|^ *\bDISTRIB_ID\b *=.*|DISTRIB_ID="BigLinux based in Manjaro Linux"|g;s|^ *\bDISTRIB_DESCRIPTION\b *=.*|DISTRIB_DESCRIPTION="BigLinux"|g' $BUILDDIR/$ARCH/usr/lib/os-release
+    # BigLinux Information
+    sed -i 's|^Manjaro Linux|BigLinux, based in Manjaro Linux|g' $BUILDDIR/$ARCH/etc/issue
+    sed -i 's|^ *\bNAME\b *=.*|NAME="BigLinux based in Manjaro Linux"|;s|^ *\ID\b *=.*|ID="biglinux-arm"|;s|^ *\ID_LIKE\b *=.*|ID_LIKE="biglinux arch"|;s|^ *\bPRETTY_NAME\b *=.*|PRETTY_NAME="BigLinux based in Manjaro Linux"|;s|^ *\ANSI_COLOR\b *=.*|ANSI_COLOR="32;1;24;144;200"|;s|^ *\bHOME_URL\b *=.*|HOME_URL="https://www.biglinux.com.br"|;s|^ *\bSUPPORT_URL\b *=.*|SUPPORT_URL="https://forum.biglinux.com.br"|;s|^ *\LOGO\b *=.*|LOGO="biglinux-blue"|' $BUILDDIR/$ARCH/usr/lib/os-release
+    sed -i 's|^ *\bDISTRIB_ID\b *=.*|DISTRIB_ID="BigLinux based in Manjaro Linux"|g;s|^ *\bDISTRIB_DESCRIPTION\b *=.*|DISTRIB_DESCRIPTION="BigLinux"|g' $BUILDDIR/$ARCH/usr/lib/os-release
 
-  # Change name on login
-  echo 'Welcome to BigLinux ARM
+    # Change name on login
+    echo 'Welcome to BigLinux ARM
 ~~Website:  https://www.biglinux.com.br
 ~~Forum:    https://forum.biglinux.com.br
 ~~Telegram: https://t.me/BigLinuxCommunity' | tee $BUILDDIR/$ARCH/etc/motd
 
-  # Add biglinux repo
-  echo '
+    # Add biglinux repo
+    echo '
 #[biglinux-testing]
 #SigLevel = PackageRequired
 SigLevel = Optional TrustAll
@@ -64,7 +64,7 @@ SigLevel = Optional TrustAll
 Server = https://repo.biglinux.com.br/stable/aarch64' | tee -a $BUILDDIR/$ARCH/etc/pacman.conf
 }
 
-compress_rootfs () {
+compress_rootfs() {
     msg "Compressing rootfs..."
     cd $BUILDDIR/$ARCH
     tar -czf $IMGDIR/BigLinux-ARM-$ARCH-latest.tar.gz .
@@ -75,23 +75,23 @@ compress_rootfs () {
 opt=":a:h"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     a)
-      ARCH="${OPTARG}"
-      ;;
+        ARCH="${OPTARG}"
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}"
-      exit 1
-      ;;
-    h|?)
-      echo "-h <help>       This help"
-      exit 1
-      ;;
+        echo "Invalid option: -${OPTARG}"
+        exit 1
+        ;;
+    h | ?)
+        echo "-h <help>       This help"
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 # Log file
diff --git a/bin/deployarmimg b/bin/deployarmimg
--- a/bin/deployarmimg
+++ b/bin/deployarmimg
@@ -15,68 +15,64 @@ enable_colors
 opt=":i:d:e:v:k:u:th"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     i)
-      IMAGE="${OPTARG}"
-      ;;
+        IMAGE="${OPTARG}"
+        ;;
     d)
-      DEVICE="${OPTARG}"
-      ;;
+        DEVICE="${OPTARG}"
+        ;;
     e)
-      EDITION="${OPTARG}"
-      ;;
+        EDITION="${OPTARG}"
+        ;;
     v)
-      VERSION="${OPTARG}"
-      ;;
+        VERSION="${OPTARG}"
+        ;;
     k)
-      GPGMAIL="${OPTARG}"
-      ;;
+        GPGMAIL="${OPTARG}"
+        ;;
     u)
-      STORAGE_USER="${OPTARG}"
-      ;;
+        STORAGE_USER="${OPTARG}"
+        ;;
     t)
-      TORRENT="true"
-      ;;
+        TORRENT="true"
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}"
-      exit 1
-      ;;
-    h|?)
-      usage_deploy_img
-      exit 1
-      ;;
+        echo "Invalid option: -${OPTARG}"
+        exit 1
+        ;;
+    h | ?)
+        usage_deploy_img
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 #required options
 if [ "x" == "x$IMAGE" ]; then
-  echo "-i [option] is required"
-  exit
+    echo "-i [option] is required"
+    exit
 fi
 if [ "x" == "x$GPGMAIL" ]; then
-  echo "-k [option] is required"
-  exit
+    echo "-k [option] is required"
+    exit
 fi
-
 
 # Create checksums for the image
 checksum_img
 
 #create torrent for image
-if [[ $TORRENT = "true" ]]
-then
-create_torrent
+if [[ $TORRENT = "true" ]]; then
+    create_torrent
 fi
 
 # Upload image + checksums to image server
 img_upload
 
-
 # remove pkg + sig from cache folder
 #msg "Removing local files..."
 #rm $image*
- 
diff --git a/bin/getarmprofiles b/bin/getarmprofiles
--- a/bin/getarmprofiles
+++ b/bin/getarmprofiles
@@ -10,28 +10,28 @@ check_root
 opt="fhp"
 
 while getopts "${opt}" arg; do
-  case $arg in
+    case $arg in
     f)
-      echo "Forcing git update..."
-      rm -rf $PROFILES/biglinux-arm-profiles
-      ;;
+        echo "Forcing git update..."
+        rm -rf $PROFILES/biglinux-arm-profiles
+        ;;
     p)
-      echo "Using branch 'pp-factory'..."
-      FACTORY=true
-      ;;
+        echo "Using branch 'pp-factory'..."
+        FACTORY=true
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}"
-      exit 1
-      ;;
-    h|?)
-      usage_getarmprofiles
-      exit 1
-      ;;
+        echo "Invalid option: -${OPTARG}"
+        exit 1
+        ;;
+    h | ?)
+        usage_getarmprofiles
+        exit 1
+        ;;
     :)
-      echo "Option -${OPTARG} requires an argument, aborting"
-      exit 1
-      ;;
-  esac
+        echo "Option -${OPTARG} requires an argument, aborting"
+        exit 1
+        ;;
+    esac
 done
 
 get_profiles
